export const ACTION_SET_CLUB_DETAIL = 'detail/CLUB_DETAIL';
export const ACTION_SET_ACTIVITY_DETAIL = 'detail/ACTIVITY_DETAIL';
export const ACTION_SET_LITERATURE_DETAIL = 'detail/LITERATURE_DETAIL';
export const ACTION_SET_HISTORICALINDEX_DETAIL = 'detail/HISTORICALINDEX_DETAIL';
export const ACTION_SET_REALOBJECT_DETAIL = 'detail/REALOBJECT_DETAIL';
export const ACTION_SET_PEOPLE_DETAIL = 'detail/PEOPLE_DETAIL';
export const ACTION_SET_JOURNAL_DETAIL = 'detail/JOURNAL_DETAIL';

export const ACTION_SET_DETAIL_LOADING = 'detail/DETAIL_LOADING';